1.2

diff --git a/master b/master
--- a/master
+++ b/master
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/bin/bash 
 #This script allows for dist-upgrade - auto-remove
 #Author: Stephen J Kennedy
-#version 1.0
+#version 1.2
 #DEBUG used with -x (reports shell name, line number, and associated function)
 PS4='+ $BASH_SOURCE : $LINENO : ${FUNCNAME[0]} ()'
 
@@ -13,47 +13,40 @@ LOG="${LOGPATH}/log/${DATE}-${PID}-log"
 TEMP="${LOGPATH}/.temp"
 MAIL=/usr/bin/mail
 TO="medicup@gmail.com"
-UPDATE="update upgrade dist-upgrade autoremove" #options for autoUpdate do statement
 
+#options for autoUpdate do statement
 #mail Function uses mail to distribute results of autoUpdate
 mailOutput(){
-case $? in
-   0)
-        echo "Success!"
-        $MAIL -s ${DATE}-${HOSTNAME}  $TO < $LOG
-      ;;
-   1)
-        echo "mail error"
-        $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
-      ;;
-   2)
-        echo "Reboot needed"
-        $MAIL -s "Reboot required for ${HOSTNAME}: shutdown pending." $TO < $LOG
-        shutdown -r now
-        kill PID
-      ;;
-esac
+   case $? in
+      0)
+         echo "Success!"
+         $MAIL -s ${DATE}-${HOSTNAME}  $TO < $LOG
+         ;;
+      1)
+         echo "mail error"
+         $MAIL -s "Error with ${HOSTNAME} update: check ${UPDATE}." $TO < $LOG
+         ;;
+      2)
+         echo "Reboot needed"
+         $MAIL -s "Reboot required for ${HOSTNAME}: shutdown pending." $TO < $LOG
+         autoremove
+         shutdown -r now
+         ;;
+   esac
 }
-
 
 #Auto-update that includes dist-upgrade
 autoUpdate (){
-echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
-for UPDATE in $UPDATE
-do
-  case "$UPDATE" in
-  [update]|[upgrade]|[dist-upgrade])
-        apt-get $UPDATE --assume-yes >> $LOG || return 1
-        ;;
-  autoremove)
-        apt-get $UPDATE >> $LOG
-        if [ -f /var/run/reboot-required ]
-           then
-                echo "Reboot required" >> $LOG && return 2
-        fi
-        ;;
-esac
-done
+   echo "Starting update for $HOSTNAME at $TIME on ${DATE}." > $LOG
+   apt-get update
+   for UPDATE in upgrade dist-upgrade
+   do
+     apt-get $UPDATE --assume-yes >> $LOG || return 1
+     if [ -f /var/run/reboot-required ]
+        then
+            echo "Reboot required" && return 2
+     fi
+   done
 }
 
 autoUpdate
